### ISSUE TITLE
Bonsai not obtaining data from Acquisition Board

### ISSUE THREAD

**Issue by theparkerlab** [open-ephys/Bonsai.OpenEphys#2]
Hello, I'm having trouble using Bonsai to acquire data from the new (OE FPGA) acquisition board. I've also posted this on the Bonsai GitHub [discussions page](https://github.com/orgs/bonsai-rx/discussions/1675). I've used Bonsai to acquire from the older Rhythm FPGA boards for years with no problem. 

I have the board working with the OE GUI, but when I use the AcquisitionBoard node in Bonsai from the community package I am unable to see any data streaming in. The workflow seems to start correctly but nothing happens (no error message, and it runs indefinitely) and nothing comes up on the visualizers. I've installed the drivers and the OE GUI plugin as described in the guide, and the gateway version is reading v1.0, which I believe is the most recent. Is there something else I'm missing?

Thanks!
Phil

![image](https://github.com/open-ephys/Bonsai.OpenEphys/assets/139789779/2e876f25-0ce5-4500-aebd-4c13c8e8e9c0)

**Comment by jsiegle** [comment]
@aacuevas any ideas about this one?

**Comment by aacuevas** [comment]
The current version of the node has a known issue in which it can take up to a minute or two to start acquiring data. Is it taking longer than that?

**Comment by theparkerlab** [comment]
Thanks for the tip - if I wait about 50-60 seconds it does start to acquire from the board, however it only seems to display one sample then results in a "Runtime Error: Unknown Error" message. I've attempted to attach a video here to show the result.

I was wondering if a full "fresh install" might help things, but I wasn't sure how to uninstall the driver. The one place I deviated from the [instructions](https://open-ephys.github.io/acq-board-docs/User-Manual/New-FPGA.html) was not installing the driver first, but the current version of the OE GUI installs the driver for you when you install the plugin. I've uninstalled and reinstalled both the OE GUI and Bonsai to no effect.

https://github.com/open-ephys/Bonsai.OpenEphys/assets/139789779/478244f3-d227-46d3-9843-dd9a5a0c6c18

**Comment by melodieborel** [comment]
Hello, I just had to deal with this issue. In my case, it was related to the clroni package that was not in a compatible version. OpenEphys package works with clroni version 5.0.0 but not with 5.0.2 (that is automatically installed if you also work with ONIX for instance). Check the clroni version installed from the package manager. If it is 5.0.2, you can try to uninstall it (it will recquire to uninstall any ONIX, Ephys and OpenEphys package first), and then reinstall OpenEphys. Once I did that, it took indeed about 15-30s to start acquiring.

**Comment by theparkerlab** [comment]
Thanks Mélodie! I received some advice from OEPS as well, and this solved my problem. I had to downgrade the USB drivers because they haven't been incorporated into Bonsai yet:

"The USB drivers were recently updated by the manufacturer so probably the Bonsai package needs to be repackaged with those...I'm now thinking that if this is the issue in the meantime you might be able to get it to work by downgrading to the previous driver version. Here are the instructions:
 
Uninstall version 1.3.0.8 of the driver and install version [1.3.0.4](https://www.ftdichip.com/Driver/D3XX/FTD3XXDriver_WHQLCertified_v1.3.0.4_Installer.exe.zip) (this is a direct link that should start the download for you)."

**Comment by jonnew** [comment]
Hey all,

Thanks for all of this information. We are working on fixing the issue with
the latest clroni and will update this thread when that work is finished.

Jon
